### PR TITLE
1.  Update to swift 5

### PR DESCRIPTION
**Pull request by wlixcc**
**1.Description of the problem:**
When I use pod to import the library, the swift version was wrong and I had to manually adjust a lot of things to work。

**2. Fix** 
Update swift version  to swift5， and fix warning in project。 
You can now run projects directly  after `pod install` without having to manually fix errors and adjust swift versions

I think author should add a new pod version 5.0.0 😊

xcode version: 12.5.1 
swift version: 5

### CODE REVIEW

**Comment by wlixcc** [comment]
@vadymmarkov  hi, can you review this pull request and add a new pod version  support swift 5. 
In my own project, I want to direct use this library and do not change any files in pod import

**Review by vadymmarkov — APPROVED** [review]
Thank you @wlixcc

**Comment by vadymmarkov** [comment]
There is a new version 5.0.0 you can use in your project 😉

**Comment by wlixcc** [comment]
@vadymmarkov Thanks, I have updated to the new version and everything seems to be working fine

**Pull request merged**
